apiVersion: v1
kind: Service
metadata:
  name: shopflow-api
  namespace: shopflow
spec:
  selector:
    app: shopflow-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
